#! /usr/bin/bash

APT_PKG="zsh discord tmux"

sudo apt update -y;


## Changes default shell to zsh
chsh -s /usr/bin/zsh

## Install Oh My ZSH
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
           